### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by fluxionary**
this PR fixes a few bugs: 
1. the `cleanse` effect needs to check that playereffects is actually present or it will crash
2. some sounds were not specified properly, and would play for everyone on the server, no matter where they were
3. use the engine to randomly select between sounds instead of lua
4. prevent leaking some variables into global scope

### CODE REVIEW

**Comment by AnnalysaTheMinetester** [comment]
Did you just... read through ALL of my code? I am so sorry that you had to try to understand all of that mess! I made such silly mistakes!! I am embarassed that i even misstyped the name of the variable! Thank you for paying attention to these details and worked on improving this cheesy mess!

Anyway, let me be clear on some "not mistakes": i wrote the gelatin variable assignment as such, due me not wanting to leave out players who dont have mods that register gelatin items that i know of, so that they would have a craft without the use of such items. I must therefor check if a mod that i know registers an item in that group is present and only then change the crafting acoordingly.

Furthermore, it seems to me that you erased some "local node" definitions just before a "set_node" to change the cheese rack. I know that it seems redundant, but i need the node due to the param2, allowing the new node in place of the old one to retain its rotation.

Anyway, thank you for your dedication! Keep up the good work!

**Comment by fluxionary** [comment]
re: gelatin: oh, i see now. however, previously, the only recipes which used gelatin (shining spume, frosted spume) were defined when ethereal was present, in which case the gelatin variable was always set to "group:food_gelatin". i've pushed a commit to check for the presence of mods which have items in group:food_gelatin instead, in case that variable is used in other recipes in the future.

**Comment by fluxionary** [comment]
and unless i missed something, the "node" parameter to the on_punch callbacks is already populated w/ the results of `minetest.get_node(pos)`, including param2. getting the node again was redundant.

**Comment by fluxionary** [comment]
also, i certainly didn't read all the code, but i did run [luacheck](https://luacheck.readthedocs.io/en/stable/) on it to find the places where variable names were wrong or leaked into the global namespace. some of the formatting changes were automatically inserted by my IDE (i wish it wouldn't do that...), but i *did* intentionally run formatting on `cauldron_node_timer`, because it appeared that `still_room_for_cooked_item` was declared in the wrong scope and i was having trouble figuring out where the right scope was. i could probably revert some of the minor, meaningless formatting changes if you wish.

**Comment by AnnalysaTheMinetester** [comment]
Fine by me then. Thank you so much for your work here. I apologize that i wasnt being able to realize these mistakes sooner and fix them.

**Pull request merged**
